#include "memchr.c"
#include "memcmp.c"
#include "memcpy.c"
#include "memset.c"
#include "strcat.c"
#include "strcpy.c"
#include "strlen.c"
#include "strncat.c"
#include "strncmp.c"
#include "strstr.c"
#include "strpos.c"
#include "libc.c"

