/*example:*/
#define __NO_LIBS_OPEN
#define __NO_LIBS_CLOSE
#define __NO_LIBS_STAT
#define __NO_LIBS_FSTAT
#define __NO_LIBS_LSTAT
#define __NO_LIBS_BRK
//#define __NO_LIBS_EXIT
#define __NO_LIBS_GETPID
#define __NO_LIBS_FORK
#define __NO_LIBS_VFORK
#define __NO_LIBS_READ
#define __NO_LIBS_LSEEK
#define __NO_LIBS_KILL
#define __NO_LIBS_DUP2
#define __NO_LIBS_DUP
#define __NO_LIBS_ALARM
#define __NO_LIBS_PIPE
#define __NO_LIBS_TIME
#define __NO_LIBS_UNLINK
#define __NO_LIBS_NANOSLEEP
#define __NO_LIBS_READLINK
#define __NO_LIBS_IOCTL
#define __NO_LIBS_SOCKET
#define __NO_LIBS_BIND
#define __NO_LIBS_ACCEPT
#define __NO_LIBS_CONNECT
#define __NO_LIBS_LISTEN
#define __NO_LIBS_GETSOCKNAME
#define __NO_LIBS_SETSOCKNAME
#define __NO_LIBS_SETSOCKOPT
#define __NO_LIBS_GETSOCKOPT
#define __NO_LIBS_SENDTO
#define __NO_LIBS_SEND
#define __NO_LIBS_RECVFROM
#define __NO_LIBS_RECV
#define __NO_LIBS_VMSPLICE
#define __NO_LIBS_TEE
#define __NO_LIBS_SPLICE
#define __NO_LIBS_SENDFILE
#define __NO_LIBS_WAITPID
#define __NO_LIBS_WAITID
#define __NO_LIBS_WAIT2
#define __NO_LIBS_WAIT
#define __NO_LIBS_CLONE
#define __NO_LIBS_SELECT
#define __NO_LIBS_FCNTL
#define __NO_LIBS_EXECVE
//#define __NO_LIBS_WRITE
#define __NO_LIBS_MPROTECT
#define __NO_LIBS_MUNMAP
#define __NO_LIBS_MMAP
#define __NO_LIBS_SBRK
#define __NO_LIBS_MREMAP
#define __NO_LIBS_MADVISE

