#include "odd.c"
#include "ltype.c"
#include "ctype.c"
#include "is_num.c"
#include "sch.c"
#include "sch_count.c"
#include "scmp.c"
#include "scpy.c"
#include "mcpy.c"
#include "msetn.c"
#include "mset.c"
#include "strnpos.c"
#include "substr_count.c"
#include "string_replace.c"
#include "mncat.c"
#include "mcat.c"
#include "set.c"
#include "print.c"


